# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CD

on:
  push:
    branches: 
          - '*'
    
  pull_request:
    branches: 
          - 'master'

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
       java-version: 1.8
       server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
       settings-path: $ # location for the settings.xml file
       
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
     
     
    - name: Build APK
      run: bash ./gradlew assembleRelease --stacktrace
     
     
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
       name: app_$
       path: app/release/app-release.apk
       
     
    - name: action-slack
      uses: 8398a7/action-slack@v3.8.0
      with:
        status: $
        author_name: 빌드 알림
      env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
